const countryCodes = [
  "AF", "AX", "AL", "DZ", "AS", "AD", "AO", "AI", "AQ", "AG", "AR", "AM",
  "AW", "AU", "AT", "AZ", "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ",
  "BM", "BT", "BO", "BQ", "BA", "BW", "BV", "BR", "IO", "BN", "BG", "BF",
  "BI", "CV", "KH", "CM", "CA", "KY", "CF", "TD", "CL", "CN", "CX", "CC",
  "CO", "KM", "CG", "CD", "CK", "CR", "CI", "HR", "CU", "CW", "CY", "CZ",
  "DK", "DJ", "DM", "DO", "EC", "EG", "SV", "GQ", "ER", "EE", "SZ", "ET",
  "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF", "GA", "GM", "GE", "DE",
  "GH", "GI", "GR", "GL", "GD", "GP", "GU", "GT", "GG", "GN", "GW", "GY",
  "HT", "HM", "VA", "HN", "HK", "HU", "IS", "IN", "ID", "IR", "IQ", "IE",
  "IM", "IL", "IT", "JM", "JP", "JE", "JO", "KZ", "KE", "KI", "KP", "KR",
  "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY", "LI", "LT", "LU", "MO",
  "MG", "MW", "MY", "MV", "ML", "MT", "MH", "MQ", "MR", "MU", "YT", "MX",
  "FM", "MD", "MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR", "NP",
  "NL", "NC", "NZ", "NI", "NE", "NG", "NU", "NF", "MK", "MP", "NO", "OM",
  "PK", "PW", "PS", "PA", "PG", "PY", "PE", "PH", "PN", "PL", "PT", "PR",
  "QA", "RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "VC",
  "WS", "SM", "ST", "SA", "SN", "RS", "SC", "SL", "SG", "SX", "SK", "SI",
  "SB", "SO", "ZA", "GS", "SS", "ES", "LK", "SD", "SR", "SJ", "SE", "CH",
  "SY", "TW", "TJ", "TZ", "TH", "TL", "TG", "TK", "TO", "TT", "TN", "TR",
  "TM", "TC", "TV", "UG", "UA", "AE", "GB", "UM", "US", "UY", "UZ", "VU",
  "VE", "VN", "VG", "VI", "WF", "EH", "YE", "ZM", "ZW",
] as const;

const regionDisplayNames = new Intl.DisplayNames(["en"], { type: "region" });

export const countryOptions = countryCodes
  .map((code) => regionDisplayNames.of(code))
  .filter((label): label is string => Boolean(label))
  .sort((a, b) => a.localeCompare(b));

export const airportOptions = [
  "AMS - Amsterdam Airport Schiphol (Amsterdam)",
  "ATL - Hartsfield-Jackson Atlanta International Airport (Atlanta)",
  "AUH - Abu Dhabi International Airport (Abu Dhabi)",
  "BCN - Barcelona-El Prat Airport (Barcelona)",
  "BER - Berlin Brandenburg Airport (Berlin)",
  "BKK - Suvarnabhumi Airport (Bangkok)",
  "BOM - Chhatrapati Shivaji Maharaj International Airport (Mumbai)",
  "BOS - Boston Logan International Airport (Boston)",
  "BRU - Brussels Airport (Brussels)",
  "CAI - Cairo International Airport (Cairo)",
  "CDG - Paris Charles de Gaulle Airport (Paris)",
  "CGK - Soekarno-Hatta International Airport (Jakarta)",
  "CLT - Charlotte Douglas International Airport (Charlotte)",
  "CPT - Cape Town International Airport (Cape Town)",
  "DEL - Indira Gandhi International Airport (Delhi)",
  "DEN - Denver International Airport (Denver)",
  "DFW - Dallas/Fort Worth International Airport (Dallas)",
  "DOH - Hamad International Airport (Doha)",
  "DUB - Dublin Airport (Dublin)",
  "DXB - Dubai International Airport (Dubai)",
  "EWR - Newark Liberty International Airport (Newark)",
  "FCO - Leonardo da Vinci-Fiumicino Airport (Rome)",
  "FRA - Frankfurt Airport (Frankfurt)",
  "GRU - Sao Paulo/Guarulhos International Airport (Sao Paulo)",
  "HKG - Hong Kong International Airport (Hong Kong)",
  "HND - Haneda Airport (Tokyo)",
  "IAH - George Bush Intercontinental Airport (Houston)",
  "ICN - Incheon International Airport (Seoul)",
  "IST - Istanbul Airport (Istanbul)",
  "JFK - John F. Kennedy International Airport (New York)",
  "JNB - O.R. Tambo International Airport (Johannesburg)",
  "KIX - Kansai International Airport (Osaka)",
  "KUL - Kuala Lumpur International Airport (Kuala Lumpur)",
  "LAS - Harry Reid International Airport (Las Vegas)",
  "LAX - Los Angeles International Airport (Los Angeles)",
  "LGW - London Gatwick Airport (London)",
  "LHR - London Heathrow Airport (London)",
  "LIS - Humberto Delgado Airport (Lisbon)",
  "MAD - Adolfo Suarez Madrid-Barajas Airport (Madrid)",
  "MCO - Orlando International Airport (Orlando)",
  "MEL - Melbourne Airport (Melbourne)",
  "MEX - Mexico City International Airport (Mexico City)",
  "MIA - Miami International Airport (Miami)",
  "MNL - Ninoy Aquino International Airport (Manila)",
  "MSP - Minneapolis-Saint Paul International Airport (Minneapolis)",
  "MUC - Munich Airport (Munich)",
  "NRT - Narita International Airport (Tokyo)",
  "ORD - O'Hare International Airport (Chicago)",
  "OSL - Oslo Airport (Oslo)",
  "PHX - Phoenix Sky Harbor International Airport (Phoenix)",
  "PRG - Vaclav Havel Airport Prague (Prague)",
  "SAN - San Diego International Airport (San Diego)",
  "SEA - Seattle-Tacoma International Airport (Seattle)",
  "SFO - San Francisco International Airport (San Francisco)",
  "SIN - Singapore Changi Airport (Singapore)",
  "SYD - Sydney Kingsford Smith Airport (Sydney)",
  "SZX - Shenzhen Bao'an International Airport (Shenzhen)",
  "TLV - Ben Gurion Airport (Tel Aviv)",
  "VIE - Vienna International Airport (Vienna)",
  "WAW - Warsaw Chopin Airport (Warsaw)",
  "YUL - Montreal-Trudeau International Airport (Montreal)",
  "YVR - Vancouver International Airport (Vancouver)",
  "YYZ - Toronto Pearson International Airport (Toronto)",
  "ZRH - Zurich Airport (Zurich)",
] as const;

export const airlineOptions = [
  "GB - ABX Air",
  "A3 - Aegean Airlines",
  "EI - Aer Lingus",
  "M0 - Aero Mongolia",
  "P5 - Aero Republica",
  "SU - Aeroflot",
  "XZ - Aeroitalia",
  "AR - Aerolineas Argentinas",
  "AM - Aeromexico",
  "AW - Africa World Airlines",
  "AH - Air Algérie",
  "G9 - Air Arabia",
  "KC - Air Astana",
  "2A - Air Astra",
  "CC - Air Atlanta Icelandic",
  "UU - Air Austral",
  "BT - Air Baltic",
  "BP - Air Botswana",
  "SM - Air Cairo",
  "TY - Air Caledonie",
  "K6 - Air Cambodia",
  "AC - Air Canada",
  "TX - Air Caraibes",
  "9H - Air Changan",
  "CA - Air China",
  "XK - Air Corsica",
  "EN - Air Dolomiti",
  "UX - Air Europa",
  "AF - Air France",
  "GL - Air Greenland",
  "GT - Air Guilin",
  "LD - Air Hong Kong",
  "AI - Air India",
  "IX - Air India Express",
  "JS - Air Koryo",
  "NX - Air Macau",
  "MK - Air Mauritius",
  "4O - Air Montenegro",
  "NZ - Air New Zealand",
  "PX - Air Niugini",
  "YW - Air Nostrum",
  "P4 - Air Peace",
  "YP - Air Premia",
  "HC - Air Senegal",
  "JU - Air Serbia",
  "HM - Air Seychelles",
  "VT - Air Tahiti",
  "TN - Air Tahiti Nui",
  "TC - Air Tanzania",
  "TS - Air Transat",
  "NF - Air Vanuatu",
  "SB - Aircalin",
  "RE - Airhub Airlines",
  "D4 - Airline GEO SKY",
  "4Z - Airlink",
  "KJ - AIRZETA",
  "VF - AJet",
  "QP - Akasa Air",
  "AS - Alaska Airlines",
  "AP - Albastar",
  "UJ - AlMasria Universal Airlines",
  "8R - Amelia",
  "AA - American Airlines",
  "NH - ANA",
  "GP - APG Airlines",
  "DM - Arajet",
  "IZ - Arkia Israeli Airlines",
  "OZ - Asiana Airlines",
  "KP - ASKY",
  "3V - ASL Airlines Belgium",
  "5O - ASL Airlines France",
  "5H - ASL Airlines Ireland",
  "RC - Atlantic Airways",
  "5Y - Atlas Air",
  "OS - Austrian",
  "AV - Avianca",
  "LR - Avianca Costa Rica",
  "2K - Avianca Ecuador",
  "X9 - Avion Express",
  "4X - Avion Express Malta",
  "J2 - Azerbaijan Airlines",
  "S4 - Azores Airlines",
  "AD - Azul Brazilian Airlines",
  "J4 - Badr Airlines",
  "UP - Bahamasair",
  "QH - Bamboo Airways",
  "PG - Bangkok Airways",
  "ID - Batik Air",
  "OD - Batik Air Malaysia",
  "B5 - BBN Airlines",
  "0B - BBN Airlines Indonesia",
  "B2 - Belavia Belarusian Airlines",
  "BG - Biman Bangladesh Airlines",
  "NT - Binter Canarias",
  "BZ - Blue Bird Airways",
  "OB - BoA Boliviana de Aviacion",
  "TF* - Braathens Regional Airways",
  "BA - British Airways",
  "SN - Brussels Airlines",
  "FB - Bulgaria Air",
  "QC - Camair-Co",
  "JD - Capital Airlines",
  "W8 - Cargojet Airways",
  "CV - Cargolux",
  "BW - Caribbean Airlines",
  "V3 - Carpatair",
  "CX - Cathay Pacific",
  "5J - Cebu Pacific",
  "5Z - CemAir",
  "CS - Chair Airlines",
  "CE - Chalair",
  "X7 - Challenge Airlines (BE)",
  "5C - Challenge Airlines (IL)",
  "EU - Chengdu Airlines",
  "CI - China Airlines",
  "CK - China Cargo Airlines",
  "MU - China Eastern",
  "G5 - China Express Airlines",
  "CF - China Postal Airlines",
  "CZ - China Southern Airlines",
  "KN - China United Airlines",
  "QG - Citilink",
  "WX - CityJet",
  "VE - Clic Air",
  "DE - Condor",
  "CM - COPA Airlines",
  "XC - Corendon Airlines",
  "SS - Corsair International",
  "OU - Croatia Airlines",
  "CU - Cubana",
  "CY - Cyprus Airways",
  "DN - DAN AIR",
  "R6* - DAT (LT)",
  "DL - Delta Air Lines",
  "D0 - DHL Air",
  "ES* - DHL Air (Bahrain)",
  "4Y - Discover Airlines",
  "SF - Domestic Airlines",
  "ZE - Eastar Jet",
  "2D* - Eastern Airlines",
  "WK - Edelweiss Air",
  "MS - Egyptair",
  "LY - EL AL",
  "3E - Electra Airways",
  "EK - Emirates",
  "E7 - Estafeta Cargo",
  "ET - Ethiopian Airlines",
  "EY - Etihad Airways",
  "YU - EuroAtlantic Airways",
  "QY - European Air Transport",
  "EW - Eurowings",
  "BR - EVA Air",
  "FN - Fastjet Zimbabwe",
  "FX - FedEx Express",
  "FJ - Fiji Airways",
  "AY - Finnair",
  "W2 - FlexFlight",
  "IF - Fly Baghdad",
  "WV - Fly Namibia",
  "F6* - Fly2Sky",
  "F3 - flyadeal",
  "FZ - flydubai",
  "J7 - FlyGabon",
  "XY - Flynas",
  "5F - FLYONE",
  "FH - Freebird Airlines",
  "BF - French Bee",
  "F9 - Frontier Airlines",
  "FU - Fuzhou Airlines",
  "GA - Garuda Indonesia",
  "A9 - Georgian Airways",
  "ZQ - German Airways",
  "GW* - GetJet Airlines",
  "GE - Global Airways and Lift",
  "G6 - GlobalX",
  "G3 - GOL Linhas Aereas",
  "HB - Greater Bay Airlines",
  "GF - Gulf Air",
  "GX - GX Airlines",
  "HR* - Hahnair",
  "HU - Hainan Airlines",
  "HA - Hawaiian Airlines",
  "NS - Hebei Airlines",
  "H3 - Hello Jets",
  "HN* - Heston Airlines",
  "5K* - Hi Fly",
  "3L* - Hi Fly (Malta)",
  "H9 - Himalaya Airlines",
  "RH - Hong Kong Air Cargo",
  "HX - Hong Kong Airlines",
  "UO - Hong Kong Express Airways",
  "IB - IBERIA",
  "6O - Iberojet (Portugal)",
  "E9 - Iberojet Airlines (Spain)",
  "QI - Ibom Air",
  "FI - Icelandair",
  "EO - Ikar",
  "6E - IndiGo",
  "IR - Iran Air",
  "B9 - Iran Airtour Airline",
  "EP - Iran Aseman Airlines",
  "6H - Israir",
  "AZ - ITA Airways",
  "JL - Japan Airlines",
  "NU - Japan Transocean Air",
  "J9 - Jazeera Airways",
  "JG - JD Airlines",
  "7C - Jeju Air",
  "B6 - JetBlue",
  "WJ - JetSMART Argentina",
  "JA - JetSMART Chile",
  "J6 - JetSMART Colombia",
  "JZ - JetSMART Peru",
  "JP* - Jettime",
  "LJ - Jin Air",
  "R5 - Jordan Aviation",
  "HO - Juneyao Airlines",
  "RQ - Kam Air",
  "KQ - Kenya Airways",
  "KJ* - KlasJet",
  "KL - KLM",
  "KM - KM Malta Airlines",
  "KE - Korean Air",
  "KY - Kunming Airlines",
  "KU - Kuwait Airways",
  "B0 - La Compagnie",
  "TM - LAM",
  "QV - Lao Airlines",
  "JJ - LATAM Airlines Brasil",
  "4C - LATAM Airlines Colombia",
  "XL - LATAM Airlines Ecuador",
  "LA - LATAM Airlines Group",
  "PZ - LATAM Airlines Paraguay",
  "LP - LATAM Airlines Peru",
  "M3 - LATAM Cargo Brasil",
  "UC - LATAM Cargo Chile",
  "FC - Link Airways",
  "JT - Lion Air",
  "LM - Loganair",
  "GJ - Loong Air",
  "LO - LOT Polish Airlines",
  "8L - Lucky Air",
  "LH - Lufthansa",
  "LH - Lufthansa Cargo",
  "VL - Lufthansa City Airlines",
  "CL - Lufthansa CityLine",
  "LG - Luxair",
  "MD - Madagascar Airlines",
  "MH - Malaysia Airlines",
  "AE - Mandarin Airlines",
  "O8 - Marathon Airlines",
  "MP - Martinair Cargo",
  "M7 - MasAir",
  "L6 - Mauritania Airlines International",
  "4M - Mavi Gök Airlines (MGA)",
  "ME - MEA",
  "OM - MIAT Mongolian Airlines",
  "MB - MNG Airlines",
  "8M - Myanmar Airways International",
  "UB - Myanmar National Airlines",
  "N8 - National Airlines",
  "ON - Nauru Airlines",
  "NO - Neos",
  "NE - Nesma Airlines",
  "NP - Nile Air",
  "KZ - Nippon Cargo Airlines",
  "DD - Nok Air",
  "Y7 - NordStar",
  "N4 - Nordwind Airlines",
  "N7 - Norra",
  "BJ - Nouvelair",
  "BK - Okay Airways",
  "OA - Olympic Air",
  "WY - Oman Air",
  "OF - Overland Airways",
  "PK - Pakistan International Airlines",
  "2P - PAL Express",
  "ZP - Paranair",
  "UF - PAS",
  "PC - Pegasus Airlines",
  "NI* - PGA-Portugalia Airlines",
  "PR - Philippine Airlines",
  "PU - Plus Ultra",
  "PO - Polar Air Cargo",
  "HP - PopulAir",
  "PD - Porter Airlines",
  "M4 - Poste Air Cargo",
  "PW - Precision Air",
  "P6 - Privilege Style",
  "P0 - Proflight Zambia",
  "QF - Qantas",
  "QR - Qatar Airways",
  "IQ - Qazaq Air",
  "QW - Qingdao Airlines",
  "4S - Red Sea Airlines",
  "RX - Riyadh Air",
  "FV - Rossiya Airlines",
  "AT - Royal Air Maroc",
  "BI - Royal Brunei",
  "RJ - Royal Jordanian",
  "DR - Ruili Airlines",
  "7R - RusLine",
  "WB - RwandAir",
  "S7 - S7 Airlines",
  "FA - Safair",
  "OV - Salam Air",
  "SK - SAS",
  "SP - SATA Air Acores",
  "SV - Saudi Arabian Airlines",
  "DV - SCAT Airlines",
  "TR - Scoot",
  "O3 - SF Airlines",
  "SC - Shandong Airlines",
  "FM - Shanghai Airlines",
  "ZH - Shenzhen Airlines",
  "3U - Sichuan Airlines",
  "7L - Silk Way West Airlines",
  "SQ - Singapore Airlines",
  "H2 - SKY Airline",
  "GQ - Sky express",
  "PQ - SkyUp Airlines",
  "5N - Smartavia",
  "N/A - SmartLynx Airlines Malta",
  "QS - Smartwings",
  "IE - Solomon Airlines",
  "SZ - Somon Air",
  "SA - South African Airways",
  "WN - Southwest Airlines",
  "2S - Southwind Airlines",
  "SG - SpiceJet",
  "UL - SriLankan Airlines",
  "JX - STARLUX Airlines",
  "SY - Sun Country Airlines",
  "XQ - SunExpress",
  "Y8 - Suparna Airlines",
  "WT - Swiftair",
  "LX - SWISS",
  "RB - Syrianair",
  "DT - TAAG Angola Airlines",
  "TA - TACA",
  "5U - TAG Airlines",
  "TI* - Tailwind Airlines",
  "TP - TAP Air Portugal",
  "RO - TAROM",
  "TG - Thai Airways International",
  "SL - Thai Lion Air",
  "GS - Tianjin Airlines",
  "TW - Trinity Airways",
  "X3 - TUIfly",
  "TU - Tunisair",
  "TK - Turkish Airlines",
  "U8 - TUS Airways",
  "GO* - ULS Airlines Cargo",
  "B7 - UNI AIR",
  "UA - United Airlines",
  "UN - United Nigeria Airlines",
  "5X - UPS Airlines",
  "U6 - Ural Airlines",
  "UQ - Urumqi Air",
  "BS - US-Bangla Airlines",
  "UT - UTair",
  "HY - Uzbekistan Airways",
  "VJ - Vietjet",
  "VN - Vietnam Airlines",
  "VS - Virgin Atlantic",
  "VA - Virgin Australia",
  "Y4 - Volaris",
  "V7 - Volotea",
  "VY - Vueling",
  "EB - Wamos Air",
  "PN - West Air",
  "WS - WestJet",
  "WI - White coloured by you",
  "WF - Wideroe",
  "2W - World2Fly",
  "MF - Xiamen Airlines",
  "TV - Xizang Airlines",
  "YG - YTO Cargo Airlines"
] as const;

export const trainCompanyOptions = [
  "Abellio",
  "Adirondack Railroad",
  "Agilis",
  "Alaska Railroad",
  "Amtrak",
  "Arriva Nederland",
  "Arriva Rail London",
  "Arriva Vlaky",
  "Astra Trans Carpatic",
  "Auckland One Rail",
  "Avanti West Coast",
  "BLS",
  "BDZ Passenger Services",
  "Brightline",
  "Caledonian Sleeper",
  "Caltrain",
  "České dráhy",
  "China Railway",
  "CFL",
  "CFR Călători",
  "Comboios de Portugal (CP)",
  "CrossCountry",
  "Deutsche Bahn",
  "DSB",
  "East Japan Railway Company (JR East)",
  "Egyptian National Railways",
  "Elron",
  "Euskotren",
  "Eurostar",
  "European Sleeper",
  "Ferrocarrils de la Generalitat de Catalunya (FGC)",
  "Ferrocarrils de la Generalitat Valenciana (FGV)",
  "Ferrovie del Sud Est",
  "Fertagus",
  "FlixTrain",
  "Gautrain",
  "Georgian Railway",
  "Go-Ahead Nordic",
  "Grand Service Express",
  "Great Journeys New Zealand",
  "Great Western Railway",
  "Greater Anglia",
  "GySEV / Raaberbahn",
  "Hellenic Train",
  "Hokkaido Railway Company (JR Hokkaido)",
  "HŽ Putnički prijevoz",
  "Iarnród Éireann / Irish Rail",
  "Indian Railways",
  "Inca Rail",
  "Indonesia Railway Company (KAI)",
  "Israel Railways",
  "Italo",
  "iryo",
  "Japan Central Railway Company (JR Central)",
  "Japan Railways",
  "Journey Beyond",
  "Keihan Electric Railway",
  "Keio Corporation",
  "Keisei Electric Railway",
  "Kenya Railways",
  "Kintetsu Railway",
  "Korail",
  "KTM Berhad",
  "Kyushu Railway Company (JR Kyushu)",
  "Leo Express",
  "LNER",
  "Long Island Rail Road",
  "LTG Link",
  "MÁV",
  "Malayan Railways (KTM)",
  "MARC Train",
  "Matterhorn Gotthard Bahn",
  "MBTA Commuter Rail",
  "Metlink",
  "Metro-North Railroad",
  "Metrolink",
  "Metrorail South Africa",
  "Metro Trains Melbourne",
  "Montenegro Railways (ŽPCG)",
  "Myanmar Railways",
  "Nankai Electric Railway",
  "National Rail",
  "New Jersey Transit",
  "Nigerian Railway Corporation",
  "Nishi-Nippon Railroad",
  "Northern",
  "Northern Ireland Railways",
  "NS - Nederlandse Spoorwegen",
  "NSW TrainLink",
  "Odakyu Electric Railway",
  "ÖBB",
  "ONCF",
  "OUIGO",
  "OUIGO España",
  "Pakistan Railways",
  "PeruRail",
  "PKP Intercity",
  "Polregio",
  "Porterbrook",
  "Queensland Rail",
  "RegioJet",
  "Regio Călători",
  "Renfe",
  "Rhätische Bahn / Rhaetian Railway",
  "Rocky Mountaineer",
  "Romanian Railways",
  "Russian Railways (RZD)",
  "Saudi Arabia Railways (SAR)",
  "ScotRail",
  "Serveis Ferroviaris de Mallorca (SFM)",
  "Shikoku Railway Company (JR Shikoku)",
  "SJ",
  "SJ Norge",
  "SNCB / NMBS",
  "SNCF",
  "SNCFT",
  "SNTF",
  "Snälltåget",
  "South African Passenger Rail Agency (PRASA)",
  "South Western Railway",
  "Southeastern",
  "Southern",
  "South Caucasus Railway",
  "South Western Railway India",
  "SR / SRT Korea",
  "Sri Lanka Railways",
  "Srbija Voz",
  "State Railway of Thailand",
  "Swiss Federal Railways (SBB CFF FFS)",
  "Sydney Trains",
  "Taiwan High Speed Rail",
  "Taiwan Railway Corporation",
  "TAZARA",
  "TCDD Taşımacılık",
  "Thameslink",
  "Tobu Railway",
  "Tokyu Railways",
  "Transdev",
  "TransPennine Express",
  "Transwa",
  "Trenitalia",
  "Trenitalia France",
  "Trenord",
  "Trenes Argentinos",
  "Tren Maya",
  "Tren Interoceánico",
  "Uganda Railways",
  "Ukrainian Railways / Ukrzaliznytsia",
  "Uzbekistan Railways",
  "V/Line",
  "VIA Rail Canada",
  "Vietnam Railways",
  "Vivi",
  "VR",
  "VR Snabbtåg",
  "Vy",
  "Vy Tåg",
  "West Japan Railway Company (JR West)",
  "WESTbahn",
  "West Midlands Railway",
  "West Coast Express",
  "Whoosh / KCIC",
  "Železničná spoločnosť Slovensko (ZSSK)",
  "Zentralbahn"
] as const;

export const busCompanyOptions = [
  "ADO",
  "Adirondack Trailways",
  "Aerobus",
  "Aircoach",
  "ALSA",
  "Andesmar",
  "Anadolu Ulaşım",
  "Andbus",
  "APM",
  "Argentina Bus",
  "Arriva",
  "Arriva Croatia",
  "Autolinee Federico",
  "Autoprevoz Banja Luka",
  "Avanza",
  "Balıkesir Uludağ",
  "Barons Bus Lines",
  "Big Sky",
  "BlaBlaCar Bus",
  "Blue Line",
  "Bolivariano",
  "BoltBus Japan",
  "Buses Ahumada",
  "Buses Fierro",
  "Buses García",
  "Buses Jet Sur",
  "Buses JM",
  "Buses Jordan",
  "Buses Tepual",
  "CATA Internacional",
  "Catarinense",
  "Centrotrans",
  "Chihuahuenses",
  "Citiliner",
  "Civa",
  "Condor Bus",
  "Cootranshuila",
  "Copetran",
  "Cotrapat",
  "Cruz del Sur",
  "Damas",
  "Daewoo Express",
  "Delta Coaches",
  "Dublin Coach",
  "Dublin Express",
  "Eagle Liner",
  "Ebus",
  "Eme Bus",
  "ETN",
  "Expreso Bolivariano",
  "Expreso Brasilia",
  "Expreso Palmira",
  "Expreso Paraguay",
  "Expreso Singer",
  "Expressway",
  "FBS",
  "Firefly Express",
  "Flecha Bus",
  "FlixBus",
  "Flexi City Connect",
  "Franja de Oro",
  "Futura",
  "Giant Ibis Transport",
  "Gontijo",
  "Green Line",
  "Greyhound",
  "Greyhound Australia",
  "Greyhound South Africa",
  "Grupo Senda",
  "Grupo Texcoco",
  "Guanabara",
  "Hife",
  "Hope Diamond Transport",
  "Indian Trails",
  "Intercape",
  "Intercape Megaliner",
  "InterCity New Zealand",
  "Intercity Xpress",
  "Interbus",
  "Itabus",
  "Jefferson Lines",
  "Jet Set Express",
  "Kamil Koç",
  "La Preferida Bus",
  "Lasta",
  "Leo Express",
  "Limoliner",
  "LL Vaya Africa",
  "MarinoBus",
  "Megabus",
  "Metro Turizm",
  "Miller Transportation",
  "Monbus",
  "Murrays Coaches",
  "National Express",
  "Neobus",
  "New York Trailways",
  "Niš-Ekspres",
  "Nilüfer Turizm",
  "Northwestern Stage Lines",
  "NSW TrainLink Coach",
  "Omnibus de México",
  "Ontario Northland",
  "Oriente",
  "OurBus",
  "Pacific Coach Lines",
  "Pamukkale Turizm",
  "Paraguay Line",
  "Peter Pan Bus Lines",
  "Polonus",
  "Premier Motor Service",
  "Primera Plus",
  "Pullman Bus",
  "Pullman General Belgrano",
  "Pullman Tur",
  "Queen Cafe Bus",
  "Quick Shuttle",
  "Rede Expressos",
  "Red Arrow",
  "RegioJet",
  "Rápido Ochoa",
  "Samar",
  "Sani Express",
  "Scottish Citylink",
  "Sindbad",
  "Socibus",
  "Southeastern Stages",
  "Swiss Express",
  "Trailways",
  "Trans Copacabana",
  "TransBrasil",
  "Transportes Chiclayo",
  "Transportes Cruz del Sur",
  "Transportes Línea",
  "Transportes Loja Internacional",
  "Transportes OCC",
  "Transportes Salta",
  "Transportes Tac",
  "Transportes Via",
  "Tufesa",
  "Turbus",
  "Union Ivkoni",
  "Util",
  "Valle del Guadiana",
  "Viação 1001",
  "Viação Cometa",
  "Viação Garcia",
  "Via Bariloche",
  "Virak Buntham",
  "Wanda Coach",
  "Washington Deluxe",
  "Willer Express",
  "Winew Reisen",
  "Yolobus"
] as const;

const intlWithSupportedValues = Intl as typeof Intl & {
  supportedValuesOf?: (key: "currency") => string[];
};

const currencyCodes = (() => {
  try {
    const values = intlWithSupportedValues.supportedValuesOf?.("currency");
    return values?.length ? values : ["EUR", "USD", "GBP"];
  } catch {
    return ["EUR", "USD", "GBP"];
  }
})();

export function formatCurrencyOption(code: string) {
  try {
    const symbol = new Intl.NumberFormat("en", {
      style: "currency",
      currency: code,
      currencyDisplay: "narrowSymbol",
    })
      .formatToParts(0)
      .find((part) => part.type === "currency")?.value;

    return symbol && symbol !== code ? `${code} (${symbol})` : code;
  } catch {
    return code;
  }
}

export const currencyOptions = currencyCodes
  .slice()
  .sort((a, b) => a.localeCompare(b))
  .map((code) => formatCurrencyOption(code));

